### ISSUE TITLE
Segfault in ABT_mutex_lock

### ISSUE THREAD

**Issue by halimamer** [pmodels/bolt#3]
Environment: 
- LLVM 3.9.1
- BOLT 1.0a1
- Argobots 1.0a1

Reproducible code:  
[bolt_abt_mtx_segf.txt](https://github.com/pmodels/bolt/files/862016/bolt_abt_mtx_segf.txt)

Error message:

``` 
[mutex.c:172] ABT_mutex_lock: 20
Segmentation fault (core dumped)
```

GDB output:

```Core was generated by ./a.out.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f64ca2426c2 in ABT_mutex_create ()
   from /usr/local/llvm-bolt-argobots/lib/../lib/libabt.so.0
 (gdb) where
 #0  0x00007f64ca2426c2 in ABT_mutex_create ()
   from /usr/local/llvm-bolt-argobots/lib/../lib/libabt.so.0
#1  0x00007f64caa75300 in __kmp_do_serial_initialize ()
    at /usr/local/src/llvm/projects/openmp/runtime/src/abt/kmp_abt_runtime.c:139
#2  0x00007f64caa75a5a in __kmp_do_middle_initialize ()
    at /usr/local/src/llvm/projects/openmp/runtime/src/abt/kmp_abt_runtime.c:363
#3  0x00007f64caa75ddb in __kmp_middle_initialize ()
    at /usr/local/src/llvm/projects/openmp/runtime/src/abt/kmp_abt_runtime.c:470
#4  0x00007f64caa99362 in __kmp_api_omp_get_num_procs ()
    at /usr/local/src/llvm/projects/openmp/runtime/src/abt/kmp_abt_ftn_entry.h:444
#5  0x0000000000400b09 in main ()```

**Comment by KavithaTipturMadhu** [comment]
Should this be closed since it's already merged?

**Comment by halimamer** [comment]
Yup. Thought it was closed automatically after merging
